### ISSUE TITLE
ipController next function

### ISSUE THREAD

**Issue by dhopwood** [bootcamp-s17/ipam-backend#29]
Do we want to blacklist certain subnet addresses as new ip addresses.

**Comment by jctu225** [comment]
Fundamentally he should be able to over ride anything. We should have a warning message of some sort, but that will probably occur on the front end. We need to inform the front end that it is a special/reserved ip address.

If that sounds good to everyone else let me know and we can close this issue.

**Comment by dhopwood** [comment]
that sounds like a good idea. I will work on catching those cases and returning a message for the front end to use.
