### ISSUE TITLE
Notes Endpoints

### ISSUE THREAD

**Issue by david-vanderhaar** [bootcamp-s17/ipam-backend#41]
Request:
Add notes endpoints.
Find notes by type and id would be ok for now. 

For example: /api/note/site/{site Id} 
This would give us access to the note for site 1. 

It would also be helpful to have the note for a site/subnet/equipment to be pulled in with the related endpoints.

For example: /api/site/1
would include the note.

**Comment by dhopwood** [comment]
Slightly confused. Both of your examples seem similar. 

Are you asking to create endpoints to return all the notes for the specified noteable_type and noteable_id? Check out how the notes table is structured. I feel like this what you are asking for.

**Comment by Brayn7** [comment]
should it be its own endpoint or should we just return notes respectively for sites subnets and equipment
