### ISSUE TITLE
equipment_type endpoint

### ISSUE THREAD

**Issue by ChaChaSlide** [bootcamp-s17/ipam-backend#42]
we need an endpoint that will give us the data from the equipment types table.
-equipment_type_id
-equipment_type_name.

**Comment by dhopwood** [comment]
Is the reliant on anything? 
Do you want a specific type depending on a certain field?
Or do you just want a list of all equipment types id's and names?

**Comment by ChaChaSlide** [comment]
just a list of the type id's and names associated with those id's. and its not related to anything.

**Comment by dhopwood** [comment]
Okay, that is ready for you if you want to pull the ip-Phase2 branch

**Comment by ChaChaSlide** [comment]
thank you!
